export const RESPONSE_MESSAGES = {
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  ADDRESS_WALLET_MUST_BE_A_STRING: 'Address wallet must be a string',
  ADDRESS_WALLET_LENGTH: 'Address wallet must be 42 characters long',
  EMAIL_MUST_BE_A_STRING: 'Email must be a string',
  EMAIL_IS_INVALID: 'Email is invalid',
  FIELD_IS_REQUIRED: 'Field is required',
  DATEOFBIRTH_MUST_BE_A_DATE: 'Date of birth must be a date',
  USER_IS_EXIST: 'User is exist',
  PIN_LENGTH_IS_6_DIGIT: 'PIN must be 6 digits long',
  PIN_IS_NUMBER: 'PIN must be a number',
  USER_NOT_FOUND: 'User not found',
  TOKEN_IS_INVALID_OR_NOT_FOUND: 'Token is invalid or not found',
  ADDRESS_WALLET_OR_PIN_IS_INVALID: 'Address wallet or pin is invalid',
  DESCRIPTION_MUST_BE_A_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH: 'Description must be less than or equal to 100 characters',
  NAME_IS_REQUIRED: 'Name is required',
  PAGE_OR_LIMIT_NOT_PROVIDED: 'Page or limit not provided',
  CONTRACT_TYPE_NOT_FOUND_OR_DELETED: 'Contract type not found or deleted',
  PARTY_SENDER_HAS_TO_BE_INDENTIFIED: 'Party sender has to be indentified',
  MESSAGE_MUST_BE_A_STRING: 'Message must be a string',
  MESSAGE_TOO_SHORT: 'Message too short',
  INVALID_ID: 'Invalid ID',
  CONTRACT_ADDRESS_MUST_BE_STRING: 'Contract address must be a string',
  CONTRACT_ADDRESS_LENGTH_MUST_BE_42_CHARACTERS: 'Contract address length must be 42 characters',
  BLOCK_ADDRESS_LENGTH_MUST_BE_66_CHARACTERS: 'Block address length must be 66 characters',
  CONTRACT_IS_NOT_FOUND: 'Contract is not found',
  CONTRACT_TITLE_LENGTH: 'Contract title length must be less than or equal to 100 characters',
  START_DATE_MUST_BE_A_VALID_DATE: 'Start date must be a valid date',
  END_DATE_MUST_BE_A_VALID_DATE: 'End date must be a valid date',
  EXECUTE_DATE_MUST_BE_A_VALID_DATE: 'Execute date must be a valid date',
  REPRESENTATIVE_NAME_LENGTH: 'The length of the representative name must be at least 2 characters',
  TAX_CODE_LENGTH: 'Tax code length must be equal to 10 characters',
  INDENTIFY_NUMBER_LENGTH: 'Indentify number length must be equal to 12 characters',
  PHONE_NUMBER_LENGTH: 'Phone number length must be equal to 10 characters',
  THE_ADDRESS_MUST_BE_PROVIDED_IN_FULL_AND_CLEARLY: 'The address must be provided in full and clearly',
  THE_DATE_IS_INVALID: 'The date must be greater than or equal to the current date.',
  PIN_NOT_SET: 'PIN not set',
  ID_MUST_BE_A_STRING: 'ID must be a string',
  PARTY_NAME_LENGTH: 'Party name length must be between 3 and 50 characters',
  PARTY_IS_EXIST: 'Party is exist',
  PARTY_INFO_NOT_FOUND: 'Party info not found',
  PARTY_INFO_IS_NOT_PROVIDED: 'Party info is not provided or incomplete',
  CONTRACT_ATTRIBUTE_VALUES_IS_NOT_PROVIDED: 'Contract attribute values is not provided or incomplete',
  VALUE_IS_REQUIRED: 'Value is required',
  CONTRACT_ATTRIBUTE_IS_NOT_FOUND: 'Contract attribute is not found',
  CONTRACT_TEMPLATE_IS_NOT_FOUND: 'Contract template is not found',
  PARTY_INFO_IS_NOT_FOUND: 'Party info is not found',
  ONE_OF_THE_PARTY_INFO_IS_NOT_FOUND: 'One of the party info is not found',
  ONE_OF_THE_CONTRACT_ATTRIBUTE_IS_NOT_FOUND: 'One of the contract attribute is not found',
  PIN_MUST_BE_A_NUMBER: 'PIN must be a number',
  PIN_IS_REQUIRED: 'PIN is required',
  PIN_IS_INVALID: 'PIN is invalid',
  PARTY_IS_NOT_FOUND: 'Party is not found',
  PARTY_INFO_IS_EXIST: 'Party info is exist',
  CONTRACT_ATTRIBUTE_VALUES_MUST_BE_PROVIDED: 'Contract attribute values must be provided',
  VALUE_MUST_BE_STRING: 'Value must be a string',
  TEMPLATE_CONTRACT_IS_NOT_FOUND: 'Template contract is not found',
  CONTRACT_TITLE_MUST_BE_STRING: 'Contract title must be a string'
}
