export const RESPONSE_MESSAGES = {
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  ADDRESS_WALLET_MUST_BE_A_STRING: 'Address wallet must be a string',
  ADDRESS_WALLET_LENGTH: 'Address wallet must be 40 characters long',
  EMAIL_MUST_BE_A_STRING: 'Email must be a string',
  EMAIL_IS_INVALID: 'Email is invalid',
  FIELD_IS_REQUIRED: 'Field is required',
  DATEOFBIRTH_MUST_BE_A_DATE: 'Date of birth must be a date',
  USER_IS_EXIST: 'User is exist',
  PIN_LENGTH_IS_6_DIGIT: 'PIN must be 6 digits long',
  PIN_IS_NUMBER: 'PIN must be a number',
  USER_NOT_FOUND: 'User not found',
  TOKEN_IS_INVALID_OR_NOT_FOUND: 'Token is invalid or not found',
  ADDRESS_WALLET_OR_PIN_IS_INVALID: 'Address wallet or pin is invalid',
  DESCRIPTION_MUST_BE_A_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH: 'Description must be less than or equal to 100 characters',
  NAME_IS_REQUIRED: 'Name is required',
  PAGE_OR_LIMIT_NOT_PROVIDED: 'Page or limit not provided',
  CONTRACT_TYPE_NOT_FOUND_OR_DELETED: 'Contract type not found or deleted'
}
